config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get 'home/choice', to: 'home#choice'

  devise_for :users, path: 'users', controllers: {
    registrations: 'users/registrations'
  }
  devise_for :owners, path: 'owners', controllers: {
    sessions: 'owners/sessions',
  }
  
  resources :orders, only: [:new, :create, :show, :index] do
    get 'owner', on: :collection
    get 'details', on: :member
    get 'evaluation', on: :member
    post 'create_order_price', on: :member
    post 'confirm', on: :member
    post 'user_cancel', on: :member
    post 'owner_cancel', on: :member
    post 'new_user_message', on: :member
    post 'new_buffet_message', on: :member
    resources :ratings, only: [:new, :create]
    get 'new_cancel_fine_charge', on: :member
    post 'cancel_with_fine', on: :member
    post 'fine_paid', on: :member
  end

  resources :buffets, only: [:show, :new, :create, :edit, :update] do
    get 'buffet_search', on: :collection
    post 'deactivate', on: :member
    post 'activate', on: :member
    resources :ratings, only: [:show]
    get 'ratings', on: :member
  end
  
  resources :event_types, only: [:show, :edit, :update, :new, :create] do
    delete 'delete_photo/:photo_id', to: 'event_types#delete_photo', as: 'delete_photo'
    get 'set_price', on: :member
    post 'deactivate', on: :member
    post 'activate', on: :member
    resources :cancel_fines, only: [:new, :create]
    resources :special_offers, only: [:new, :create]
  end


  namespace :api do
    namespace :v1 do
      resources :buffets, only: [:index, :show] do
        resources :event_types, only: [:index]
      end
      get 'availability_check', to: 'event_types#availability_check'
    end
  end
end

app/models/buffet.rb
class Buffet < ApplicationRecord
  belongs_to :owner

  validates :name, :corporate_name, :cnpj, :address, :neighborhood, :city, :state, :email, :phone, :zipcode, presence: true
  validates :cnpj, :corporate_name, uniqueness: true
  validates :cnpj, :phone, :zipcode, format: { :with => /\A[0-9]+\z/, :message => "Deve conter apenas números" }
  validates :zipcode, length: { is: 8, :message => "Deve conter 8 dígitos." }
  validates :phone, length: { in: 10..11, :message => "Deve conter entre 10 a 11 dígitos."}
  validates :email, presence: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }

  validates :pix, :debit, :credit, :cash, inclusion: { in: [true, false] }  
  validate :at_least_one_true

  enum status: { deactivated: 0, active: 1 }

  has_many :event_types
  has_many :orders
  has_many :ratings
  has_many :fine_charges

  def average_rating
    total_ratings = ratings.count
    return nil if total_ratings.zero?

    total_grades = ratings.sum(:grade)
    total_grades.to_f / total_ratings
  end

  def has_any_price?
    event_types.joins(:price).exists?
  end

  def at_least_one_true
    unless pix || debit || credit || cash
      errors.add(:base, "Deve registrar pelo menos um método de pagamento.")
    end
  end
end

app/controllers/api/v1/buffets_controller.rb
class Api::V1::BuffetsController < Api::V1::ApiController
  def index
    if params[:query].present?
      buffets = Buffet.left_joins(:event_types).where("buffets.name LIKE ?", 
                                                      "%#{params[:query]}%").order(name: :asc).distinct
      buffets = buffets.reject { |buffet| buffet.status == 'deactivated' }
    else
      buffets = Buffet.all.order(:name)
      buffets = buffets.reject { |buffet| buffet.status == 'deactivated' }
    end
    
    buffets_with_average_rating = buffets.map do |buffet|
      buffet.as_json(except: [:created_at, :updated_at]).merge(average_rating: buffet.average_rating)
    end

    render status: 200, json: buffets_with_average_rating
  end

  def show
    buffet = Buffet.find(params[:id])
    render status: 200, json: buffet.as_json(except: [:created_at, 
                                                      :updated_at, 
                                                      :corporate_name, 
                                                      :cnpj]).merge(average_rating: buffet.average_rating)
    end
end

app/controllers/buffets_controller.rb
class BuffetsController < ApplicationController
  before_action :authenticate_owner!, only: [:new, :create, :edit, :update]
  before_action :set_buffet_check_owner, only: [:edit, :update, :deactivate, :activate]
  skip_before_action :redirect_owner_to_buffet_creation, only: [:new, :create]
  before_action :buffet_deactivated?, only: [:show]

  def new
    if current_owner.buffet == nil
      @buffet = Buffet.new
    else
      redirect_to buffet_path(current_owner.buffet.id), notice: 'Você já cadastrou um Buffet.'
    end
  end

  def show
    @buffet = Buffet.find(params[:id])
  end

  def create
    if current_owner.buffet == nil
      @buffet = Buffet.new(buffet_params)
      @buffet.owner = current_owner
      if @buffet.valid?
        @buffet.save!
        redirect_to @buffet, notice: "Buffet cadastrado com sucesso."
      else
        flash.now[:notice] = "Buffet não cadastrado."
        render 'new'
      end
    else
      redirect_to buffet_path(current_owner.buffet.id), notice: 'Você já cadastrou um Buffet.'
    end
  end

  def edit;  end
  
  def update
    if @buffet.update(buffet_params)
      redirect_to buffet_path(@buffet.id), notice: 'Buffet alterado com sucesso.'
    else
      flash.now[:notice] = "Não foi possível atualizar o Buffet"
      render 'edit'
    end
  end

  def deactivate
    @buffet.deactivated!
    redirect_to @buffet, notice: 'Buffet desativado com sucesso!'
  end

  def activate
    @buffet.active!
    redirect_to @buffet, notice: 'Buffet ativado com sucesso!'
  end

  def buffet_search
    @query = params["query"]
    buffets = Buffet.left_joins(:event_types).where("buffets.name LIKE :query OR 
                                                      buffets.city LIKE :query OR 
                                                      event_types.name LIKE :query", 
                                                      query: "%#{@query}%").order(name: :asc).distinct

    buffets_to_remove = buffets.select do |buffet|
      event_types = buffet.event_types
      event_type_names = event_types.pluck(:name)
      event_type_deactivated = event_types.any? { |event_type| event_type.status == 'deactivated' }
      
      query_matched_only_with_deactivated = event_type_names.any? { |name| name.downcase.include?(@query.downcase) } && 
                                            event_type_names.count == 1 && 
                                            event_type_deactivated
      
      query_matched_only_with_deactivated
    end
    
    buffets -= buffets_to_remove

    buffets = buffets.reject { |buffet| buffet.status == 'deactivated' }
    
    @buffets = buffets
  end

  def ratings
    @buffet = Buffet.find(params[:id])
    @ratings = Rating.list(@buffet)
  end

  private

  def buffet_params
    params.require(:buffet).permit(
      :name, :corporate_name,
      :cnpj, :address, :neighborhood,
      :city, :state, :email,
      :phone, :zipcode,
      :description, :pix,
      :debit, :credit, :cash)
  end

  def set_buffet_check_owner
    @buffet = Buffet.find(params[:id])
    if @buffet.owner != current_owner
      return redirect_to root_path, alert: 'Você não pode editar este Buffet.'
    end
  end

  def buffet_deactivated?
    @buffet = Buffet.find(params[:id])
    if @buffet.status == 'deactivated' && @buffet.owner != current_owner
      flash[:alert] = "Esse Buffet está desativado."
      redirect_to root_path
    end
  end
end

app/views/buffets/_form.html.erb
<%= form_with(model: @buffet) do |f| %>
  <div class="mb-3">
    <%= f.label :name, class: 'form-label' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :description, class: 'form-label' %>
    <%= f.text_area :description, class: 'form-control', rows: 3 %>
    <small class="form-text text-muted">Um texto que descreva o seu Buffet.</small>
  </div>

  <div class="mb-3">
    <%= f.label :corporate_name, class: 'form-label' %>
    <%= f.text_field :corporate_name, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :cnpj, class: 'form-label' %>
    <%= f.text_field :cnpj, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :address, class: 'form-label' %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :neighborhood, class: 'form-label' %>
    <%= f.text_field :neighborhood, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :city, class: 'form-label' %>
    <%= f.text_field :city, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :state, class: 'form-label' %>
    <%= f.text_field :state, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :email, class: 'form-label' %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :phone, class: 'form-label' %>
    <%= f.text_field :phone, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :zipcode, class: 'form-label' %>
    <%= f.text_field :zipcode, class: 'form-control' %>
  </div>

  <div class="border-card-7 mb-3">
    <dl>
      <dt>Métodos de Pagamento:</dt>
    <dd></dd>
      <%= f.check_box :pix, class: 'form-check-input' %>
      <%= f.label :pix, class: 'form-check-label' %>
    </dd>
    <dd></dd>
      <%= f.check_box :debit, class: 'form-check-input' %>
      <%= f.label :debit, class: 'form-check-label' %>
    </dd>
    <dd></dd>
      <%= f.check_box :credit, class: 'form-check-input' %>
      <%= f.label :credit, class: 'form-check-label' %>
    </dd>
    <dd></dd>
      <%= f.check_box :cash, class: 'form-check-input' %>
      <%= f.label :cash, class: 'form-check-label' %>
    </dd>
    </dl>
  </div>

  <div class="text-center">
    <%= f.submit 'Registrar', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/buffets/buffet_search.html.erb
<div class="border-card-7" style="padding: 10px;">
  <div class="container mt-3" style="width: 600px;">
    <h2>Resultados da Busca por: <%= @query %></h2>
    <p class="text-center">
      <%= @buffets.count %> 
      <%= Buffet.model_name.human(count: @buffets.count) %> 
      <%= I18n.translate(:found, count: @buffets.count) %>
    </p>
    
    <% if @buffets.any? %>
      <div class="list-group">
        <div id="buffets">
          <% @buffets.each do |buffet| %>
            <div class="text-center">
              <%= link_to buffet.name, buffet, class: "list-group-item list-group-item-action" %>
            </div>
          <% end %>
        </div>
      <% else %>
        <p class="text-muted">Nenhum resultado encontrado.</p>
      <% end %>
    </div>
  </div>
</div>

app/views/buffets/edit.html.erb
<div class="border-card-7" style="padding: 10px;">
  <div class="container mt-3" style="width: 600px;">
    <h2 class="text-center">Alterar Buffet</h2>

    <% if @buffet.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <ul>
          <% @buffet.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= render 'form' %>
    <div class="mb-3 text-center">
      <%= link_to 'Voltar', :back, class: "btn btn-secondary mt-3" %>
    </div>
  </div>
</div>

app/views/buffets/new.html.erb
<div class="border-card-7" style="padding: 10px;">
  <div class="container mt-3" style="width: 600px;">
    <h2 class="text-center">Cadastrar Buffet</h2>

    <% if @buffet.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <ul>
          <% @buffet.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= render 'form' %>
  </div>
</div>

app/views/buffets/ratings.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="border-card-7">
        <h3 class="text-center">Avaliações do Buffet <%= @buffet.name %></h3>
      </div>

      <div class="mt-3 mb-4 text-center">
        <%= link_to 'Voltar', @buffet, class: "btn btn-secondary" %>
      </div>

      <% @ratings.each do |rating| %>
        <%= link_to "/buffets/#{@buffet.id}/ratings/#{rating.id}", class: "card-link invisible-link" do %>
          <div class="border-card-8 row">
            <h5 class="text-center"><%= rating.event_type.name %> em <%= rating.order.date %></h5>
            <div class="col-md-6">
              <p><strong>Nota: </strong><%= rating.grade %></p>
              <p><strong>Comentário: </strong><%= rating.text %></p>
            </div>
            <div class="col-md-6">
              <% rating.photos.each do |photo| %>
                <div class="mr-2 mb-2">
                  <%= image_tag photo.variant(resize_to_fit: [120, 80]) %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>

      <div class="mt-3 mb-4 text-center">
        <%= link_to 'Voltar', @buffet, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>

app/views/buffets/show.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="border-card-6">
        <h1 class="text-center">Buffet: <%= @buffet.name %></h1>
        <h4 class="text-center"><%= @buffet.description if @buffet.description %></h4>
      </div>
    </div>
  </div>
  
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="border-card-7">
        <dl class="row">
          <% if @buffet.owner == current_owner %>
            <div class="text-center mb-3">
                <% if @buffet.active? %>
                  <%= button_to 'Desativar Buffet', deactivate_buffet_path, method: :post, class: "btn btn-danger btn-margin" %>
                <% else %>
                  <%= button_to 'Ativar Buffet', activate_buffet_path, method: :post, class: "btn btn-success btn-margin" %>
                <% end %>
            </div>
            <% status_class = case @buffet.status %>
              <% when 'active' then 'text-success' %>
              <% when 'deactivated' then 'text-danger' %>
              <% else '' %>
            <% end %>
            <dt class="col-sm-4 text-sm-right text-end">Status:</dt>
            <dd class="col-sm-8 text-sm-left <%= status_class %>"><strong><%= I18n.t(@buffet.status) %></strong></dd>
          <% end %>

          <% if @buffet.ratings.any? %>
            <dt class="col-sm-4 text-sm-right text-end">Nota do Buffet (0 - 5):</dt>
            <dd class="col-sm-8 text-sm-left"><%= sprintf("%.1f", @buffet.average_rating) %></dd>
          <% end %>

          <dt class="col-sm-4 text-sm-right text-end"">Localização:</dt>
          <dd class="col-sm-8 text-sm-left">
            <%= @buffet.address %>, <%= @buffet.neighborhood %>, <%= @buffet.city %> - <%= @buffet.state %>, <%= @buffet.zipcode %>
          </dd>

          <% payment_methods = [] %>
          <% payment_methods << Buffet.human_attribute_name(:pix) if @buffet.pix %>
          <% payment_methods << Buffet.human_attribute_name(:debit) if @buffet.debit %>
          <% payment_methods << Buffet.human_attribute_name(:credit) if @buffet.credit %>
          <% payment_methods << Buffet.human_attribute_name(:cash) if @buffet.cash %>
          <% if payment_methods.any? %>
            <dt class="col-sm-4 text-sm-right text-end"">Métodos de Pagamento:</dt>
            <dd class="col-sm-8 text-sm-left">
              <%= payment_methods.join(', ') %>
            </dd>
          <% end %>
          
          <dt class="col-sm-4 text-sm-right text-end"">E-mail:</dt>
          <dd class="col-sm-8 text-sm-left"><%= @buffet.email %></dd>
          
          <dt class="col-sm-4 text-sm-right text-end"">Telefone:</dt>
          <dd class="col-sm-8 text-sm-left"><%= @buffet.phone %></dd>
          
          <dt class="col-sm-4 text-sm-right text-end"">CNPJ:</dt>
          <dd class="col-sm-8 text-sm-left"><%= @buffet.cnpj %></dd>
        </dl>
      </div>
    </div>
  </div>
</div>

<div class="border-card-5">
  <div class="row">
    <div class="col">
      <% if @buffet.owner == current_owner %>
        <div class="text-center mt-3">
            <%= link_to 'Editar Buffet', edit_buffet_path, class: "btn btn-warning btn-margin" %>
            <%= link_to 'Adicionar Tipo de Evento', new_event_type_path, class: "btn btn-info btn-margin" %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="container mt-3">
    <h3 class="text-center">Tipos de eventos do Buffet <%= @buffet.name %></h3>
    
    <% if @buffet.event_types.empty? %>
      <div class="alert alert-warning" role="alert">
        Ainda não há Tipos de Eventos cadastrados para este Buffet.
      </div>
    <% else %>
      <div class="container mt-3">
        <div class="row justify-content-center">
          <% @buffet.event_types.each_with_index do |event, index| %>
            <% if index % 4 == 0 && index != 0 %>
              </div><div class="row justify-content-center">
            <% end %>
            <% unless event.deactivated? && event.buffet.owner != current_owner %>
              <div class="col-md-3 mb-4">
                <div class="card h-100">
                  <% if event.cover_photo.attached? %>
                    <%= image_tag event.cover_photo, class: "card-img-top" %>
                  <% end %>
                  <div class="card-body">
                    <%= link_to event.name, event, class: "stretched-link card-title h5" %>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
      <% if !owner_signed_in? && @buffet.has_any_price? %>
      <div class="mt-3 mb-4 text-center">
        <%= link_to 'Novo Pedido', new_order_path(buffet_id: @buffet.id), class: "btn btn-success" %>
      </div>
      <% elsif !owner_signed_in? && !@buffet.has_any_price? %>
        <strong class="text-warning">Eventos do Buffet ainda não possuem preços definidos.</strong>
      <% end %>
    <% end %>
  </div>
</div>

<% if @buffet.ratings.any? %>
  <div class="row justify-content-center">
    <div class="col-auto" style="width: 800px;">
      <div class="border-card-7">
        <div class="container mt-3">
          <div class="row justify-content-center">
            <h3 class="text-center mb-3">Avaliações do Buffet</h3>
          </div>
          <% Rating.top_three(@buffet).each do |rating| %>
            <%= link_to "/buffets/#{@buffet.id}/ratings/#{rating.id}", class: "card-link invisible-link" do %>
              <div class="border-card-8 row">
                <h5 class="text-center"><%= rating.event_type.name %> em <%= rating.order.date %></h5>
                <div class="col-md-6">
                  <p><strong>Nota: </strong><%= rating.grade %></p>
                  <p><strong>Comentário: </strong><%= rating.text %></p>
                </div>
                <div class="col-lg-6">
                  <% rating.photos.each do |photo| %>
                    <span class="mr-2 mb-2">
                      <%= image_tag photo.variant(resize_to_fit: [120, 80]) %>
                    </span>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>

          <% if @buffet.ratings.count > 3 %>
            <div class="text-center">
              <%= link_to 'Ver Todas', ratings_buffet_path, class: "btn btn-info" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>


</div>
  <div class="mt-3 mb-4 text-center">
    <%= link_to 'Voltar', :back, class: "btn btn-secondary" %>
  </div>
</div>