config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get 'home/choice', to: 'home#choice'

  devise_for :users, path: 'users', controllers: {
    registrations: 'users/registrations'
  }
  devise_for :owners, path: 'owners', controllers: {
    sessions: 'owners/sessions',
  }
  
  resources :orders, only: [:new, :create, :show, :index] do
    get 'owner', on: :collection
    get 'details', on: :member
    get 'evaluation', on: :member
    post 'create_order_price', on: :member
    post 'confirm', on: :member
    post 'user_cancel', on: :member
    post 'owner_cancel', on: :member
    post 'new_user_message', on: :member
    post 'new_buffet_message', on: :member
    resources :ratings, only: [:new, :create]
    get 'new_cancel_fine_charge', on: :member
    post 'cancel_with_fine', on: :member
    post 'fine_paid', on: :member
  end

  resources :buffets, only: [:show, :new, :create, :edit, :update] do
    get 'buffet_search', on: :collection
    post 'deactivate', on: :member
    post 'activate', on: :member
    resources :ratings, only: [:show]
    get 'ratings', on: :member
  end
  
  resources :event_types, only: [:show, :edit, :update, :new, :create] do
    delete 'delete_photo/:photo_id', to: 'event_types#delete_photo', as: 'delete_photo'
    get 'set_price', on: :member
    post 'deactivate', on: :member
    post 'activate', on: :member
    resources :cancel_fines, only: [:new, :create]
    resources :special_offers, only: [:new, :create]
  end


  namespace :api do
    namespace :v1 do
      resources :buffets, only: [:index, :show] do
        resources :event_types, only: [:index]
      end
      get 'availability_check', to: 'event_types#availability_check'
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :buffet
  belongs_to :event_type
  belongs_to :user

  has_one :order_price
  has_one :chat
  has_one :rating
  has_one :fine_charge

  validates :date, :guest_quantity, presence: true
  validates :guest_quantity, numericality: { greater_than: 0 }
  validate :date_is_future, on: :create
  validate :address_mandatory_if_location_elsewhere
  validate :max_guest_quantity
  validate :event_type_needs_to_have_prices

  enum location: { buffet_address: 0, elsewhere: 1 }
  enum status: { pending: 0, approved: 1, confirmed: 2, cancelled: 9}
  enum rating_status: { unrated: 0, rated: 1}

  before_validation :generate_code, on: :create

  def cancel_fines_apply?
    return false unless event_type.cancel_fines.any?
  
    event_type.cancel_fines.each do |cancel_fine|
      if (Date.today + cancel_fine.days.days) >= date
        return true
      end
    end
  
    false
  end
  

  private

  def generate_code
    self.code = SecureRandom.alphanumeric(20)
  end

  def date_is_future
    if self.date.present? && self.date <= Date.today
      self.errors.add(:date, "deve ser no futuro.")
    end
  end

  def address_mandatory_if_location_elsewhere
    self.errors.add(:address, "deve ser preenchido.") if self.location == 'elsewhere' && self.address == ''
    self.errors.add(:city, "deve ser preenchido.") if self.location == 'elsewhere' && self.city == ''
    self.errors.add(:state, "deve ser preenchido.") if self.location == 'elsewhere' && self.state == ''
    self.errors.add(:zipcode, "deve ser preenchido.") if self.location == 'elsewhere' && self.zipcode == ''
    if self.location == 'elsewhere' && self.zipcode != ''
      self.errors.add(:zipcode, "deve conter apenas números") unless zipcode.match?(/\A[0-9]+\z/)
      self.errors.add(:zipcode, "deve conter 8 dígitos.") if self.zipcode.length != 8
    end
  end

  def max_guest_quantity
    if self.guest_quantity.present? && self.guest_quantity > self.event_type.max_people.to_i
      self.errors.add(:guest_quantity, "deve ser menor ou igual a #{self.event_type.max_people.to_i}.")
    end
  end

  def event_type_needs_to_have_prices
    if self.event_type.price == nil
      self.errors.add(:event_type_id, "deve ter preços definidos.")
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :show, :index, :confirm, 
                                            :new_user_message, :user_cancel,
                                            :new_cancel_fine_charge, :cancel_with_fine]
  before_action :set_order_check_user, only: [:show, :confirm, :new_user_message, 
                                              :user_cancel, :new_cancel_fine_charge,
                                              :cancel_with_fine]
  before_action :authenticate_owner!, only: [:owner, :details, :evaluation, 
                                              :create_order_price, :new_buffet_message,
                                              :owner_cancel, :fine_paid]
  before_action :set_order_check_owner, only: [:details, :evaluation, :new_buffet_message,
                                              :owner_cancel, :fine_paid]
  before_action :check_expired_orders, only: [:owner, :index, :show, :details]
  
  def new
    buffet = Buffet.find(params[:buffet_id])

    if buffet.deactivated?
      redirect_to root_path, notice: 'O Buffet está desativado.'
    end

    @event_types = buffet.event_types.where(status: 'active')
    @order = Order.new
    @preset_event = params[:preset_event]
  end

  def create
    order_params = params.require(:order).permit(:event_type_id, :date, :guest_quantity, :details, 
                                                :location, :address, :city, :state, :zipcode)
    @order = Order.new(order_params)
    @order.buffet = @order.event_type.buffet

    if @order.buffet.deactivated?
      return redirect_to root_path, notice: 'O Buffet está desativado.'
    end

    if @order.event_type.deactivated?
      return redirect_to @order.buffet, notice: 'Esse Tipo de Evento está desativado.'
    end

    @order.user = current_user
    @order.build_chat

    if @order.valid?
      @order.save!
      redirect_to @order, notice: 'Pedido criado com sucesso.'
    else
      @buffet = @order.buffet
      @event_types = @buffet.event_types
      flash.now[:notice] = 'Não foi possível criar o pedido.'
      render :new
    end
  end

  def show
    @order_price = @order.order_price unless @order.order_price.nil?
    @chat = @order.chat
  end

  def index
    @user = current_user
    @pending_orders = Order.where(user: @user, status: 'pending')
    @approved_orders = Order.where(user: @user, status: 'approved')
    @confirmed_orders = Order.where(user: @user, status: 'confirmed')
    @cancelled_orders = Order.where(user: @user, status: 'cancelled')
  end

  def confirm
    if @order.order_price.expiration_date >= Date.today
      @order.confirmed!
      redirect_to @order, notice: 'Pedido confirmado com sucesso!'
    else
      redirect_to @order, alert: 'Proposta expirada.'
    end
  end

  def user_cancel
    @order.cancelled!
    redirect_to @order, notice: 'Pedido cancelado com sucesso!'
  end

  def owner_cancel
    @order.cancelled!
    redirect_to details_order_path(@order), notice: 'Pedido cancelado com sucesso!'
  end

  def details
    @orders = current_owner.buffet.orders.where(date: @order.date)
    @order_price = @order.order_price unless @order.order_price.nil?
    @chat = @order.chat
  end
  
  def evaluation
    @orders = current_owner.buffet.orders.where(date: @order.date)
    @order_price = OrderPrice.new(base: calculate_base_price(@order))
  end

  def create_order_price
    @order = Order.find(params[:id])
    @orders = current_owner.buffet.orders.where(date: @order.date)

    if @order.approved?
      old_price = @order.order_price
    end

    @order.order_price.destroy if @order.order_price != nil

    @order_price = OrderPrice.new(params.require(:order_price).permit(:discount, :fee, :payment, :description, :expiration_date))
    @order_price.discount ||= 0
    @order_price.fee ||= 0
    @order_price.base = calculate_base_price(@order)
    @order_price.total = @order_price.base - @order_price.discount + @order_price.fee
    @order_price.order = @order
    @order_price.event_type = @order.event_type
    @order_price.buffet = @order.buffet

    if @order_price.valid?
      @order_price.save!
      @order.update(status: 'approved')
      redirect_to details_order_path(@order), notice: 'Pedido aprovado com sucesso.'
    else
      @order.order_price = old_price.dup if old_price
      render :evaluation, alert: 'Não foi possível aprovar o pedido.'
    end
  end

  def owner
    @buffet = current_owner.buffet
    @pending_orders = Order.where(buffet: @buffet, status: 'pending')
    @approved_orders = Order.where(buffet: @buffet, status: 'approved')
    @confirmed_orders = Order.where(buffet: @buffet, status: 'confirmed')
    @cancelled_orders = Order.where(buffet: @buffet, status: 'cancelled')
  end
  
  def new_cancel_fine_charge
    cancel_fines = @order.event_type.cancel_fines
  
    applicable_fines = cancel_fines.select do |cancel_fine|
      (Date.today + cancel_fine.days.days) >= @order.date
    end
  
    if applicable_fines.any?
      applicable_fine = applicable_fines.min_by(&:days)
      @value = (applicable_fine.percentage.to_f * @order.order_price.total.to_f)/100.0
    else
      flash[:alert] = "Não foram encontradas Multas por Cancelamento."
    end
  end

  def cancel_with_fine
    value = params[:value]
    FineCharge.create!(order: @order, user: @order.user, buffet: @order.buffet, value: value)
    @order.cancelled!
    redirect_to @order, notice: 'Pedido cancelado com sucesso. Multa aplicada.'
  end

  def fine_paid
    fine = FineCharge.where(order: @order).first
    fine.paid!
    redirect_to details_order_path(@order), notice: 'Multa definida como Paga.'
  end

  def new_user_message
    @user_message = UserMessage.new(params.require(:user_message).permit(:content))
    @user_message.user = current_user
    @user_message.chat = @order.chat

    if @user_message.valid?
      @user_message.save!
      redirect_to @order, notice: 'Mensagem enviada com sucesso.'
    else
      redirect_to @order, notice: 'Não foi possível enviar a mensagem.'
    end
  end

  def new_buffet_message
    @buffet_message = BuffetMessage.new(params.require(:buffet_message).permit(:content))
    @buffet_message.buffet = current_owner.buffet
    @buffet_message.chat = @order.chat

    if @buffet_message.valid?
      @buffet_message.save!
      redirect_to details_order_path(@order), notice: 'Mensagem enviada com sucesso.'
    else
      redirect_to details_order_path(@order), notice: 'Não foi possível enviar a mensagem.'
    end
  end

  private

  def set_order_check_owner
    @order = Order.find(params[:id])
    if @order.buffet.owner != current_owner
      return redirect_to root_path, alert: 'Você não possui acesso a esse pedido.'
    end
  end

  def set_order_check_user
    @order = Order.find(params[:id])
    if @order.user != current_user
      return redirect_to root_path, alert: 'Você não possui acesso a esse pedido.'
    end
  end

  def calculate_base_price(order)
    if order.date.saturday? && order.event_type.price.weekend? || order.date.sunday? && order.event_type.price.weekend?
      base_price = order.event_type.price.weekend_base
      extra_person_price = @order.event_type.price.weekend_extra_person
      min_people = order.event_type.min_people.to_f
      base_price + (extra_person_price * (order.guest_quantity - min_people))
    else
      base_price = order.event_type.price.base
      extra_person_price = order.event_type.price.extra_person
      min_people = order.event_type.min_people.to_f
      base_price + (extra_person_price * (order.guest_quantity - min_people))
    end
  end

  def check_expired_orders
    expired_orders = Order.joins(:order_price)
                           .where('order_prices.expiration_date <= ?', Date.today)

    expired_orders.each do |expired_order|
      expired_order.cancelled!
    end
  end
  
  def event_type_deactivated?
    @event_type = EventType.find(params[:event_type_id])
    if @event_type.status == 'deactivated'
      flash[:alert] = "Esse Tipo de Evento está desativado."
      redirect_to root_path
    end
  end
end

app/views/orders/evaluation.html.erb
  <div class="row justify-content-center">
    <% if @orders.any? && @orders.count > 1 %>
      <p class="notice alert alert-info" role="alert">Existem outros pedidos para a mesma data:
      <% @orders.each do |o| %>
        <% unless o == @order %>
          <br>
          <%= link_to o.code, details_order_path(o) %>
        <% end %>
      <% end %></p>
    <% end %>
  </div>

  <% if @order_price.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <ul>
        <% @order_price.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="border-card-7">
  <h2>Avaliando Pedido de <%= @order.event_type.name %> </h2>
  <br>
  <div class="row justify-content-center">
    <div class="col">
      <dl class="row">

        <dt class="col-sm-3"><%= Order.human_attribute_name(:user_id) %>:</dt>
        <dd class="col-sm-9"><%= @order.user.name %> (<%= @order.user.email %>)</dd>

        <dt class="col-sm-3"><%= Order.human_attribute_name(:status) %>:</dt>
        <% if @order.status == 'pending' %>
          <dd class="col-sm-9"><span class="text-warning"><%= I18n.translate(@order.status) %></span></dd>
        <% elsif @order.status == 'approved' %>
          <dd class="col-sm-9"><span class="text-primary"><%= I18n.translate(@order.status) %></span></dd>
        <% elsif @order.status == 'confirmed' %>
          <dd class="col-sm-9"><span class="text-success"><%= I18n.translate(@order.status) %></span></dd>
        <% elsif @order.status == 'cancelled' %>
          <dd class="col-sm-9"><span class="text-danger"><%= I18n.translate(@order.status) %></span></dd>
        <% end %>

        <dt class="col-sm-3"><%= Order.human_attribute_name(:date) %>:</dt>
        <dd class="col-sm-9"><%= @order.date %></dd>

        <dt class="col-sm-3"><%= Order.human_attribute_name(:guest_quantity) %>:</dt>
        <dd class="col-sm-9"><%= @order.guest_quantity %></dd>

        <dt class="col-sm-3"><%= Order.human_attribute_name(:location) %>:</dt>
        <dd class="col-sm-9"><%= I18n.translate(@order.location) %></dd>

        <dt class="col-sm-3"><%= Order.human_attribute_name(:details) %>:</dt>
        <dd class="col-sm-9"><%= @order.details %></dd>

        <dt class="col-sm-3"><%= Order.human_attribute_name(:code) %>:</dt>
        <dd class="col-sm-9"><%= @order.code %></dd>

      </dl>
    </div>
  <div class="col">
    <%= form_with(model: [@order, @order_price], url: create_order_price_order_path(@order), method: :post, local: true) do |f| %>
      <div class="form-group mb-3">
        <h5><%= f.label :base, class: 'form-label' %>: R$ <span id="base_amount"><%= @order_price.base %></span></h5>
      </div>

      <div class="form-group mb-3">
        <%= f.label :discount, class: 'form-label', for: 'discount_field' %>:
        <%= f.number_field :discount, step: '0.01', class: 'form-control', id: 'discount_field' %>
      </div>

      <div class="form-group mb-3">
        <%= f.label :fee, class: 'form-label', for: 'fee_field' %>:
        <%= f.number_field :fee, step: '0.01', class: 'form-control', id: 'fee_field' %>
      </div>

      <div class="border-card-3">
        <h5><%= f.label :total, class: 'form-label' %>: R$ <span id="updated_amount">0.00</span></h5>
      </div>

      <div class="form-group mb-3">
        <%= f.label :description, class: 'form-label' %>
        <%= f.text_area :description, class: 'form-control' %>
        <small class="form-text text-muted">Caso haja um desconto ou taxa extra, deve ser explicado aqui o motivo.</small>
      </div>

      <div class="form-group mb-3"></div>
        <%= f.label :payment, class: 'form-label' %>
        <% ['pix', 'debit', 'credit', 'cash'].each do |payment_method| %>
          <% if @order.buffet.public_send(payment_method) %>
            <div class="form-check">
              <%= f.radio_button :payment, payment_method, class: 'form-check-input', id: "payment_#{payment_method}" %>
              <%= f.label :payment, Buffet.human_attribute_name(:"#{payment_method}"), value: payment_method, class: 'form-check-label', for: "payment_#{payment_method}" %>
            </div>
          <% end %>
        <% end %>
      </div>

      <div class="form-group mb-3">
        <%= f.label :expiration_date, class: 'form-label' %>
        <%= f.date_field :expiration_date, class: 'form-control' %>
        <small class="form-text text-muted">Até quando vale esta proposta.</small>
      </div>
      
      <div class="mt-4">
        <%= f.submit 'Aprovar Pedido', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-12 col-md-8 text-center">
    <%= link_to 'Voltar', details_order_path(@order), class: "btn btn-secondary" %>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    var baseSpan = document.getElementById('base_amount');
    var discountInput = document.getElementById('discount_field');
    var feeInput = document.getElementById('fee_field');
    var updatedAmount = document.getElementById('updated_amount');

    function calculateAndUpdateTotal() {
      var base = parseFloat(baseSpan.textContent) || 0;
      var discount = parseFloat(discountInput.value) || 0;
      var fee = parseFloat(feeInput.value) || 0;

      var total = base - discount + fee;
      updatedAmount.textContent = total.toFixed(2);
    }

    discountInput.addEventListener('input', calculateAndUpdateTotal);
    feeInput.addEventListener('input', calculateAndUpdateTotal);

    calculateAndUpdateTotal();
  });
</script>

app/views/orders/new_cancel_fine_charge.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="border-card-7" style="width: 600px;">
      <h3 class="mb-4 text-center text-danger">Alerta!</h3>
      <h4 class="mb-4 text-center">O Cancelamento do Pedido acarretará na cobrança da seguinte multa:</h3>
      <h4 class="mb-4 text-center">R$ <%= @value %></h4>
      <div class="row justify-content-center">
        <div class="col-auto">
          <%= button_to 'Confirmar Cancelamento', cancel_with_fine_order_path(value: @value), method: :post, class: "btn btn-danger pe-3 ps-3" %>
        </div>
        <div class="col-auto">
          <%= link_to 'Voltar', :back, class: "btn btn-secondary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/orders/show.html.erb
<div class="border-card-7">
  <div class="row justify-content-center">
    <h2>Pedido de <%= @order.event_type.name %> </h2>
  </div>
  <div class="row justify-content-center">
    <div class="col">
      <div class="buffet">
        <h4><%= Order.human_attribute_name(:buffet) %> <%= link_to @order.buffet.name, @order.buffet, class: "invisible-link" %></h4>
      </div>
      <div class="border-card">
        <div class="card-body">
          <dl class="row">
            <dt class="col-sm-5"><%= Order.human_attribute_name(:status) %>:</dt>
            <% if @order.status == 'pending' %>
              <dd class="col-sm-7"><span class="text-warning"><%= I18n.translate(@order.status) %></span></dd>
            <% elsif @order.status == 'approved' %>
              <dd class="col-sm-7"><span class="text-primary"><%= I18n.translate(@order.status) %></span></dd>
            <% elsif @order.status == 'confirmed' %>
              <dd class="col-sm-7"><strong class="text-success"><%= I18n.translate(@order.status) %></strong></dd>
            <% elsif @order.status == 'cancelled' %>
              <dd class="col-sm-7"><span class="text-danger"><%= I18n.translate(@order.status) %></span></dd>
            <% end %>

            <dt class="col-sm-5"><%= Order.human_attribute_name(:date) %>:</dt>
            <dd class="col-sm-7"><%= @order.date %></dd>

            <dt class="col-sm-5"><%= Order.human_attribute_name(:guest_quantity) %>:</dt>
            <dd class="col-sm-7"><%= @order.guest_quantity %></dd>

            <dt class="col-sm-5"><%= Order.human_attribute_name(:location) %>:</dt>
            <dd class="col-sm-7"><%= I18n.translate(@order.location) %></dd>

            <% if @order.location == 'elsewhere' %>
              <dl>
                <dt class="col-sm-5"><%= Order.human_attribute_name(:address) %>:</dt>
                <dd class="col-sm-7"><%= @order.address %>, <%= @order.city %> - <%= @order.state %>, <%= @order.zipcode %></dd>
              </dl>
            <% end %>

            <% if !@order.details.empty? && @order.details != nil %>
              <dt class="col-sm-5"><%= Order.human_attribute_name(:details) %>:</dt>
              <dd class="col-sm-7"><%= @order.details %></dd>
            <% end %>

            <dt class="col-sm-5"><%= Order.human_attribute_name(:code) %>:</dt>
            <dd class="col-sm-7"><%= @order.code %></dd>
          </div>
        </div>

        <% if @order.status == 'approved' || @order.status == 'confirmed' %>
          <div class="border-card">
            <div class="card-body">
              <h5 class="text-primary">Proposta do Buffet:</h5>
              
                <dt class="col-sm-5"><%= OrderPrice.human_attribute_name(:base) %>: </dt>
                <dd class="col-sm-7">R$ <%= @order_price.base %></dd>

                <% if @order_price.discount > 0 %>
                  <dt class="col-sm-5"><%= OrderPrice.human_attribute_name(:discount) %>:</dt>
                  <dd class="col-sm-7">R$ <%= @order_price.discount %></dd>
                <% elsif @order_price.fee > 0 %>
                  <dt class="col-sm-5"><%= OrderPrice.human_attribute_name(:fee) %>:</dt>
                  <dd class="col-sm-7">R$ <%= @order_price.fee %></dd>
                <% end %>
                
                <% unless @order_price.base == @order_price.total %>
                  <dt class="col-sm-5"><%= OrderPrice.human_attribute_name(:description) %>:</dt>
                  <dd class="col-sm-7"><%= @order_price.description %></dd>

                  <dt class="col-sm-5"><%= OrderPrice.human_attribute_name(:total) %>:</dt>
                  <dd class="col-sm-7">R$ <%= @order_price.total %></dd>
                <% end %>

                <dt class="col-sm-5"><%= OrderPrice.human_attribute_name(:payment) %>:</dt>
                <dd class="col-sm-7"><%= I18n.t(@order_price.payment) %></dd>

                <dt class="col-sm-5"><%= OrderPrice.human_attribute_name(:expiration_date) %>:</dt>
                <dd class="col-sm-7"><%= @order_price.expiration_date %></dd>
            </div>
          </div>
        <% end %>
      </dl>
    </div>
    <% unless @order.status == 'cancelled' %>
      <div class="col">
        <div class="buffet">
          <h4>Converse com o <%= Order.human_attribute_name(:buffet) %> <%= link_to @order.buffet.name, @order.buffet, class: "invisible-link" %></h4>
        </div>
        <div class="border-card">
          <div class="border-card-3" id="chat-box" style="height: 250px; overflow-y: scroll;">
            <% @chat.messages.each do |message| %>
              <div class="border-card-4 message-card <%= message.is_a?(UserMessage) ? 'message-user' : 'message-buffet' %> <%= message.is_a?(UserMessage) ? 'message-user-color' : 'message-buffet-color' %>">
                <div class="card-body-2">
                  <p class="card-text">
                    <% if message.is_a?(UserMessage) %>
                      <strong>Você: </strong>
                    <% elsif message.is_a?(BuffetMessage) %>
                      <strong>Buffet <%= message.buffet.name %>:</strong> 
                    <% end %>
                    <%= message.content %>
                  </p>
                  <p class="card-text">
                    <small class="text-muted"><%= UserMessage.human_attribute_name(:created_at) %>: <%= message.created_at.strftime("%d %b %Y %H:%M") %></small>
                  </p>
                </div>
              </div>
            <% end %>
          </div>
          <%= form_with(model: [@order, UserMessage.new], url: new_user_message_order_path(@order), method: :post, local: true) do |f| %>
            <div class="form-group mb-3">
              <%= f.label :content, class: 'form-label' %>:
              <%= f.text_area :content, class: 'form-control' %>
            </div>
            <div class="mt-4">
              <%= f.submit 'Enviar', class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
    <div class="row">
      <% if @order.status == 'confirmed' && @order.date < Date.today && @order.unrated? %>
        <div class="col-auto">
          <%= link_to 'Avaliar Buffet', new_order_rating_path(order_id: @order.id), class: "btn btn-success pe-3 ps-3" %>
        </div>
      <% end %>
      <% if @order.rated? %>
        <div class="col-auto">
          <%= link_to 'Avaliação Enviada!', "/buffets/#{@order.buffet.id}/ratings/#{@order.rating.id}", class: "btn btn-outline-success" %>
        </div>
      <% end %>
      <% if @order.status == 'approved' && @order.order_price.expiration_date >= Date.today %>
        <div class="col-auto">
          <%= button_to 'Confirmar Pedido', confirm_order_path, method: :post, class: "btn btn-success pe-3 ps-3" %>
        </div>
      <% end %>
      <% if @order.status != 'cancelled' && @order.status != 'confirmed' || (@order.status == 'confirmed' && !@order.cancel_fines_apply?)  %>
        <div class="col-auto">
          <%= button_to 'Cancelar Pedido', user_cancel_order_path, method: :post, class: "btn btn-danger pe-3 ps-3", id: "cancel-order-btn" %>
        </div>
      <% end %>
      <% if @order.status == 'confirmed' && @order.cancel_fines_apply?  %>
        <div class="col-auto">
          <%= link_to 'Cancelar Pedido', new_cancel_fine_charge_order_path, class: "btn btn-danger pe-3 ps-3" %>
        </div>
      <% end %>
      <div class="col-auto">
        <%= link_to 'Voltar', orders_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
  <div class="row">
    <% if @order.event_type.cancel_fines.any? %>
      <div class="col-6">
        <div class="border-card-7">
          <h4 class="text-center">Multas por Cancelamento:</h4>
          <% @order.event_type.cancel_fines.each do |fine| %>
            <div class="border-card-3">
              <dl>
                <dd><strong>Dias antes da Data do Evento: </strong><%= fine.days %></dd>
                <dd><strong>Porcentagem da Multa: </strong><%= fine.percentage %>%</dd>
              </dl>
              <small class="form-text text-muted">Essa multa é aplicada apenas para eventos confirmados que forem cancelados a <%= fine.days %> dias ou menos antes da data do evento.</small>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
    <% if @order.cancelled? && @order.fine_charge %>
      <div class="col-6">
        <div class="border-card-7">
          <% if @order.fine_charge.pending? %>
            <h4 class="text-center text-danger">Multa Pendente de R$ <%= @order.fine_charge.value %></h4>
          <% else %>
            <h4 class="text-center text-success">Multa de R$ <%= @order.fine_charge.value %> Paga.</h4>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

    
<script>
document.addEventListener("DOMContentLoaded", function() {
  const chatBox = document.getElementById("chat-box");
  if (chatBox) {
    chatBox.scrollTop = chatBox.scrollHeight;
  }

  const cancelButton = document.getElementById("cancel-order-btn");
  if (cancelButton) {
    cancelButton.addEventListener('click', function(event) {
      if (!confirm('Tem certeza?')) {
        event.preventDefault();
      }
    });
  }
});
</script>