config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get 'home/choice', to: 'home#choice'

  devise_for :users, path: 'users', controllers: {
    registrations: 'users/registrations'
  }
  devise_for :owners, path: 'owners', controllers: {
    sessions: 'owners/sessions',
  }
  
  resources :orders, only: [:new, :create, :show, :index] do
    get 'owner', on: :collection
    get 'details', on: :member
    get 'evaluation', on: :member
    post 'create_order_price', on: :member
    post 'confirm', on: :member
    post 'user_cancel', on: :member
    post 'owner_cancel', on: :member
    post 'new_user_message', on: :member
    post 'new_buffet_message', on: :member
    resources :ratings, only: [:new, :create]
    get 'new_cancel_fine_charge', on: :member
    post 'cancel_with_fine', on: :member
    post 'fine_paid', on: :member
  end

  resources :buffets, only: [:show, :new, :create, :edit, :update] do
    get 'buffet_search', on: :collection
    post 'deactivate', on: :member
    post 'activate', on: :member
    resources :ratings, only: [:show]
    get 'ratings', on: :member
  end
  
  resources :event_types, only: [:show, :edit, :update, :new, :create] do
    delete 'delete_photo/:photo_id', to: 'event_types#delete_photo', as: 'delete_photo'
    get 'set_price', on: :member
    post 'deactivate', on: :member
    post 'activate', on: :member
    resources :cancel_fines, only: [:new, :create]
    resources :special_offers, only: [:new, :create]
  end


  namespace :api do
    namespace :v1 do
      resources :buffets, only: [:index, :show] do
        resources :event_types, only: [:index]
      end
      get 'availability_check', to: 'event_types#availability_check'
    end
  end
end

app/controllers/api/v1/event_types_controller.rb
class Api::V1::EventTypesController < Api::V1::ApiController
  def index
    buffet = Buffet.find(params[:buffet_id])
    events = buffet.event_types.includes(:price)
    events = events.reject { |events| events.status == 'deactivated' }

    events_json = events.map do |event_type|
      json_data = event_type.as_json(except: [:created_at, :updated_at])
      
      if event_type.price.present?
        json_data[:price] = event_type.price.as_json(except: [:created_at, :updated_at])
      end

      json_data
    end
    render status: 200, json: events_json
  end

  def availability_check
    event = EventType.find(params[:event_type_id])
    date = params[:date].to_date
    guests = params[:guests].to_f
    warnings = []

    future_date = true if date > Date.today

    date_conflict = event.orders.where(date: date, status: ['approved', 'confirmed'])
    
    if date_conflict.empty?
      if guests <= event.max_people.to_f
        if date.saturday? && event.price.weekend? || date.sunday? && event.price.weekend?
          base_price = event.price.weekend_base
          extra_person_price = event.price.weekend_extra_person
          min_people = event.min_people.to_f
          value = base_price + (extra_person_price * (guests - min_people))

          result = { 'price': value }
        else
          base_price = event.price.base
          extra_person_price = event.price.extra_person
          min_people = event.min_people.to_f
          if guests >= min_people
            value = base_price + (extra_person_price * (guests - min_people))
          else
            value = base_price
          end

          result = { 'price': value }
        end
      else
        warnings << 'Quantidade de convidados acima do limite.'

        result = { 'warnings': warnings }
      end
    else
      warnings << 'O Buffet já possui um evento marcado para esta data.'

      result = { 'warnings': warnings }
    end
    
    result = { 'warnings': ['A data do evento deve ser no futuro.'] } if future_date != true

    render status: 200, json: result.as_json
  end
end

app/controllers/event_types_controller.rb
class EventTypesController < ApplicationController
  before_action :authenticate_owner!, only: [:new, :create, :edit, :update, :set_price]
  before_action :set_event_type_check_owner, only: [:edit, :update, :set_price, :deactivate, :activate]
  before_action :event_type_deactivated?, only: [:show]

  def new
    @event_type = EventType.new
  end

  def create
    @event_type = EventType.new(event_type_params)
    @event_type.buffet = current_owner.buffet
    if @event_type.valid?
      @event_type.save!
      redirect_to @event_type, notice: "Tipo de Evento cadastrado com sucesso."
    else
      flash.now[:notice] = "Tipo de Evento não cadastrado."
      render 'new'
    end
  end

  def show
    @event_type = EventType.find(params[:id])
  end

  def edit
    @event_type.build_price if !@event_type.price
  end

  def update
    if @event_type.update(event_type_params)
      redirect_to event_type_path(@event_type.id), notice: 'Tipo de Evento alterado com sucesso.'
    else
      flash.now[:notice] = "Não foi possível atualizar o Tipo de Evento"
      if @event_type.errors.details.keys.any? { |error_key| error_key.to_s.start_with?('price.') }
        render 'set_price'
      else
        render 'edit'
      end
    end
  end
  
  def deactivate
    @event_type.deactivated!
    redirect_to @event_type, notice: 'Tipo de Evento desativado com sucesso!'
  end
  
  def activate
    @event_type.active!
    redirect_to @event_type, notice: 'Tipo de Evento ativado com sucesso!'
  end

  def delete_photo
    @event_type = EventType.find(params[:event_type_id])
    photo = @event_type.gallery_photos.find(params[:photo_id])

    if @event_type.buffet != current_owner.buffet
      return redirect_to root_path, alert: 'Você não pode editar este Tipo de Evento.'
    end
    
    photo.purge
  
    redirect_to @event_type, notice: 'Foto apagada com sucesso.'
  end
  
  def set_price
    @event_type.price.destroy if @event_type.price
    @event_type.build_price
  end

  private

  def event_type_params
    params.require(:event_type).permit(
      :name, :description, :cover_photo,
      :min_people, :max_people,
      :duration, :menu, :alcohol,
      :decoration, :parking,
      :location, price_attributes: [:base, 
                                    :extra_person, 
                                    :extra_hour, 
                                    :weekend_base, 
                                    :weekend_extra_person, 
                                    :weekend_extra_hour],
                                    gallery_photos: [])
  end

  def set_event_type_check_owner
    @event_type = EventType.find(params[:id])
    if @event_type.buffet != current_owner.buffet
      return redirect_to root_path, alert: 'Você não pode editar este Tipo de Evento.'
    end
  end

  def event_type_deactivated?
    @event_type = EventType.find(params[:id])
    if @event_type.status == 'deactivated' && @event_type.buffet.owner != current_owner
      flash[:alert] = "Esse Tipo de Evento está desativado."
      redirect_to root_path
    end
  end
end

app/views/event_types/_form.html.erb
<%= form_with(model: @event_type) do |f| %>
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="mb-3">
        <%= f.label :name, class: 'form-label' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="mb-3">
        <%= f.label :description, class: 'form-label' %>
        <%= f.text_area :description, class: 'form-control' %>
        <small class="form-text text-muted">Um texto que descreva o Tipo de Evento.</small>
      </div>
      <div class="mb-3">
        <%= f.label :cover_photo, class: 'form-label' %>
        <%= f.file_field :cover_photo, class: 'form-control' %>
        <small class="form-text text-muted">Uma foto que represente o seu evento. Será exibida na capa.</small>
      </div>
      <% if @event_type.persisted? && @event_type.gallery_photos.attached? %>
        <div class="mb-3">
          <% @event_type.gallery_photos.each do |photo| %>
            <%= f.hidden_field :gallery_photos, multiple: true, value: photo.signed_id if photo.blob.persisted? %>
          <% end %>
        </div>
      <% end %>
      <div class="mb-3">
        <%= f.label :gallery_photos, class: 'form-label' %>
        <%= f.file_field :gallery_photos, multiple: true, class: 'form-control' %>
      </div>
      <div class="mb-3">
        <%= f.label :min_people, class: 'form-label' %>
        <%= f.text_field :min_people, class: 'form-control' %>
        <small class="form-text text-muted">O preço base do seu evento leva em conta esse valor.</small>
      </div>
      <div class="mb-3">
        <%= f.label :max_people, class: 'form-label' %>
        <%= f.text_field :max_people, class: 'form-control' %>
      </div>
      <div class="mb-3">
        <%= f.label :duration, class: 'form-label' %>
        <%= f.text_field :duration, class: 'form-control' %>
      </div>
      <div class="mb-3">
        <%= f.label :menu, class: 'form-label' %>
        <%= f.text_area :menu, class: 'form-control' %>
      </div>
      <div class="mb-3 form-check">
        <%= f.check_box :alcohol, class: 'form-check-input' %>
        <%= f.label :alcohol, class: 'form-check-label' %>
      </div>
      <div class="mb-3 form-check">
        <%= f.check_box :decoration, class: 'form-check-input' %>
        <%= f.label :decoration, class: 'form-check-label' %>
      </div>
      <div class="mb-3 form-check">
        <%= f.check_box :parking, class: 'form-check-input' %>
        <%= f.label :parking, class: 'form-check-label' %>
      </div>
      <div class="mb-3">
        <%= f.label :location, EventType.human_attribute_name(:location), class: 'form-label' %>
        <% EventType.locations.each do |key, value| %>
          <div class="form-check">
            <%= f.radio_button :location, key, class: 'form-check-input' %>
            <%= f.label :location, EventType.human_attribute_name("location.#{key}"), value: key, class: 'form-check-label' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col text-center">
      <%= f.submit 'Registrar', class: 'btn btn-primary mt-4' %>
    </div>
  </div>
<% end %>

app/views/event_types/edit.html.erb
<div class="border-card-7" style="padding: 10px;">
  <div class="container mt-4 text-center">
    <h2>Editar Tipo de Evento</h2>

    <% if @event_type.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <ul>
          <% @event_type.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>

    <%= render 'form' %>

  <div class="row">
    <div class="col text-center">
      <%= link_to 'Voltar', @event_type, class: "btn btn-secondary mt-3" %>
    </div>
  </div>
</div>

app/views/event_types/new.html.erb
<div class="border-card-7" style="padding: 10px;">
  <div class="container mt-4 text-center">
    <h1>Novo Tipo de Evento</h1>

    <% if @event_type.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <strong>Por favor, corrija os seguintes erros:</strong>
        <ul>
          <% @event_type.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  </div>

  <%= render 'form' %>

  <div class="row">
    <div class="col text-center">
      <%= link_to 'Voltar', :back, class: "btn btn-secondary mt-3" %>
    </div>
  </div>
</div>

app/views/event_types/set_price.html.erb
<div class="border-card-7" style="padding: 10px;">
  <div class="container mt-4 text-center">
    <h2>Definir Preços</h2>

    <% if @event_type.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <ul>
          <% @event_type.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    </div><%= form_with(model: @event_type) do |f| %>
      <div class="row justify-content-center">
        <div class="col-md-6">
          <%= f.fields_for :price do |price_f| %>
            <div class="mb-3">
              <%= price_f.label :base, Price.human_attribute_name(:base), class: 'form-label' %>
              <%= price_f.number_field :base, step: '0.01', class: 'form-control' %>
              <small class="form-text text-muted">Esse valor é correspondente ao número mínimo de pessoas do Tipo de Evento.</small>
            </div>
            <div class="mb-3">
              <%= price_f.label :extra_person, Price.human_attribute_name(:extra_person), class: 'form-label' %>
              <%= price_f.number_field :extra_person, step: '0.01', class: 'form-control' %>
              <small class="form-text text-muted">Esse valor é correspondente a cada pessoa excedente à quantidade mínima de convidados.</small>
            </div>
            <div class="mb-3">
              <%= price_f.label :extra_hour, Price.human_attribute_name(:extra_hour), class: 'form-label' %>
              <%= price_f.number_field :extra_hour, step: '0.01', class: 'form-control' %>
            </div>
            <div class="mb-3">
              <%= price_f.label :weekend_base, Price.human_attribute_name(:weekend_base), class: 'form-label' %>
              <%= price_f.number_field :weekend_base, step: '0.01', class: 'form-control' %>
              <small class="form-text text-muted">Você pode definir um preço diferenciado para o final de semana. Opcional.</small>
            </div>
            <div class="mb-3">
              <%= price_f.label :weekend_extra_person, Price.human_attribute_name(:weekend_extra_person), class: 'form-label' %>
              <%= price_f.number_field :weekend_extra_person, step: '0.01', class: 'form-control' %>
            </div>
            <div class="mb-3">
              <%= price_f.label :weekend_extra_hour, Price.human_attribute_name(:weekend_extra_hour), class: 'form-label' %>
              <%= price_f.number_field :weekend_extra_hour, step: '0.01', class: 'form-control' %>
            </div>
          <% end %>
        </div>
      </div>
    <div class="row justify-content-center">
      <div class="col text-center">
        <%= f.submit 'Registrar', class: 'btn btn-primary mt-4' %>
        <%= link_to 'Voltar', @event_type, class: 'btn btn-secondary mt-4' %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/event_types/show.html.erb
<div class="container mt-4" style="padding: 10px">
  <div class="row justify-content-center">
    <div class="col-6 text-center">
      <div class="border-card-5" style="padding: 20px;">
        <div>
          <h1><%= @event_type.name %></h1>
          <% if @event_type.cover_photo.attached? %>
            <%= image_tag @event_type.cover_photo.variant(resize_to_limit: [400, 300])%>
          <% end %>
        </div>

        <% if !owner_signed_in? && @event_type.price %>
        <br>
        <div>
          <%= link_to 'Novo Pedido', new_order_path(buffet_id: @event_type.buffet.id, preset_event: @event_type), 
                                                                                      class: "btn btn-success" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
  <% if @event_type.gallery_photos.attached? %>
    <div class="row justify-content-center">
      <div class="col-12 text-center">
        <div class="border-card-5 d-flex flex-wrap justify-content-center" id="gallery">
          <% @event_type.gallery_photos.each do |photo| %>
            <div class="mr-2 mb-2" style="padding: 2px;">
              <%= image_tag photo.variant(resize_to_limit: [300, 200]), class: "mb-1" %>
              <% if @event_type.buffet.owner == current_owner %>
                <%= button_to 'Apagar', event_type_delete_photo_path(event_type_id: @event_type.id, 
                                                                    photo_id: photo.id), method: :delete, 
                                                                    class: 'btn btn-danger btn-sm' %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="row justify-content-center">
    <div class="col-12">
      <div class="border-card-7">
        <dl class="row">
          <% if @event_type.buffet.owner == current_owner %>
            <div class="text-center mb-3">
              <%= link_to 'Criar Promoção', new_event_type_special_offer_path(@event_type), class: "btn, btn-success" %>
            </div>
            <div class="text-center mb-3">
                <% if @event_type.active? %>
                  <%= button_to 'Desativar Tipo de Evento', deactivate_event_type_path, method: :post, class: "btn btn-danger" %>
                <% else %>
                  <%= button_to 'Ativar Tipo de Evento', activate_event_type_path, method: :post, class: "btn btn-success" %>
                <% end %>
            </div>
            <% status_class = case @event_type.status %>
              <% when 'active' then 'text-success' %>
              <% when 'deactivated' then 'text-danger' %>
              <% else '' %>
            <% end %>
            <dt class="col-sm-3 text-sm-right">Status:</dt>
            <dd class="col-sm-9 text-sm-left <%= status_class %>"><strong><%= I18n.t(@event_type.status) %></strong></dd>
          <% end %>

          <dt class="col-sm-3"><%= EventType.human_attribute_name(:description) %>:</dt>
          <dd class="col-sm-9"><%= @event_type.description %></dd>

          <dt class="col-sm-3"><%= EventType.human_attribute_name(:duration) %>:</dt>
          <dd class="col-sm-9"><%= @event_type.duration %></dd>

          <dt class="col-sm-3"><%= EventType.human_attribute_name(:min_people) %>:</dt>
          <dd class="col-sm-9"><%= @event_type.min_people %></dd>

          <dt class="col-sm-3"><%= EventType.human_attribute_name(:max_people) %>:</dt>
          <dd class="col-sm-9"><%= @event_type.max_people %></dd>

          <dt class="col-sm-3"><%= EventType.human_attribute_name(:menu) %>:</dt>
          <dd class="col-sm-9"><%= @event_type.menu %></dd>

          <dt class="col-sm-3"><%= EventType.human_attribute_name(:location) %>:</dt>
          <dd class="col-sm-9"><%= I18n.translate(@event_type.location) %></dd>

          <% unless EventType.extras(@event_type.id).empty? %>
            <dt class="col-sm-3">Extras:</dt>
            <dd class="col-sm-9">
              <% EventType.extras(@event_type.id).each do |extra| %>
                <%= EventType.human_attribute_name(extra) %>
              <% end %>
            </dd>
          <% end %>
        </dl>
      </div>
    </div>
  </div>

  <div class="border-card-7">
    <% if @event_type.price != nil %>
      <div class="row justify-content-center">
        <div class="col">
          <% if @event_type.special_offers.any? %>
            <% @event_type.special_offers.each do |offer| %>
              <% unless offer.end < Date.today %>
                <h4 class="text-success">Promoção: Desconto de <%= offer.percentage %>% dos dias <%= offer.start %> a <%= offer.end %></h4>
              <% end %>
            <% end %>
          <% end %>
          <h3>Preços</h3>
          <dl class="row">
            <% unless @event_type.price.base == nil %>
              <dt class="col-sm-3"><%= Price.human_attribute_name(:base) %>:</dt>
              <dd class="col-sm-9">R$ <%= @event_type.price.base %></dd>
            <% end %>

            <% unless @event_type.price.extra_person == nil %>
              <dt class="col-sm-3"><%= Price.human_attribute_name(:extra_person) %>:</dt>
              <dd class="col-sm-9">R$ <%= @event_type.price.extra_person %></dd>
            <% end %>

            <% unless @event_type.price.extra_hour == nil %>
              <dt class="col-sm-3"><%= Price.human_attribute_name(:extra_hour) %>:</dt>
              <dd class="col-sm-9">R$ <%= @event_type.price.extra_hour %></dd>
            <% end %>

            <% unless @event_type.price.weekend_base == nil %>
              <dt class="col-sm-3"><%= Price.human_attribute_name(:weekend_base) %>:</dt>
              <dd class="col-sm-9">R$ <%= @event_type.price.weekend_base %></dd>
            <% end %>

            <% unless @event_type.price.weekend_extra_person == nil %>
              <dt class="col-sm-3"><%= Price.human_attribute_name(:weekend_extra_person) %>:</dt>
              <dd class="col-sm-9">R$ <%= @event_type.price.weekend_extra_person %></dd>
            <% end %>

            <% unless @event_type.price.weekend_extra_hour == nil %>
              <dt class="col-sm-3"><%= Price.human_attribute_name(:weekend_extra_hour) %>:</dt>
              <dd class="col-sm-9">R$ <%= @event_type.price.weekend_extra_hour %></dd>
            <% end %>
          </dl>
        </div>
      </div>
    <% else %>
      <strong class="text-warning">Evento ainda não possui preços definidos.</strong>
    <% end %>
  </div>
  <% if @event_type.cancel_fines.any? %>
  <div class="row justify-content-center">
    <div class="col-6">
      <div class="border-card-7">
        <h4 class="text-center">Multas por Cancelamento:</h4>
        <% @event_type.cancel_fines.each do |fine| %>
          <div class="border-card-3">
            <dl>
              <dd><strong>Dias antes da Data do Evento: </strong><%= fine.days %></dd>
              <dd><strong>Porcentagem da Multa: </strong><%= fine.percentage %>%</dd>
            </dl>
            <small class="form-text text-muted">Essa multa é aplicada apenas para eventos confirmados que forem cancelados a <%= fine.days %> dias ou menos antes da data do evento.</small>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 text-center">
      <% if @event_type.buffet.owner == current_owner %>
        <%= link_to 'Definir Preços', set_price_event_type_path, class: "btn btn-warning" %>
        <%= link_to 'Definir Multa por Cancelamento', new_event_type_cancel_fine_path(@event_type), class: "btn btn-danger" %>
        <%= link_to 'Editar Tipo de Evento', edit_event_type_path, class: "btn btn-primary" %>
      <% end %>
      <%= link_to 'Voltar', @event_type.buffet, class: "btn btn-secondary" %>
    </div>
  </div>
</div>