config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get 'home/choice', to: 'home#choice'

  devise_for :users, path: 'users', controllers: {
    registrations: 'users/registrations'
  }
  devise_for :owners, path: 'owners', controllers: {
    sessions: 'owners/sessions',
  }
  
  resources :orders, only: [:new, :create, :show, :index] do
    get 'owner', on: :collection
    get 'details', on: :member
    get 'evaluation', on: :member
    post 'create_order_price', on: :member
    post 'confirm', on: :member
    post 'user_cancel', on: :member
    post 'owner_cancel', on: :member
    post 'new_user_message', on: :member
    post 'new_buffet_message', on: :member
    resources :ratings, only: [:new, :create]
    get 'new_cancel_fine_charge', on: :member
    post 'cancel_with_fine', on: :member
    post 'fine_paid', on: :member
  end

  resources :buffets, only: [:show, :new, :create, :edit, :update] do
    get 'buffet_search', on: :collection
    post 'deactivate', on: :member
    post 'activate', on: :member
    resources :ratings, only: [:show]
    get 'ratings', on: :member
  end
  
  resources :event_types, only: [:show, :edit, :update, :new, :create] do
    delete 'delete_photo/:photo_id', to: 'event_types#delete_photo', as: 'delete_photo'
    get 'set_price', on: :member
    post 'deactivate', on: :member
    post 'activate', on: :member
    resources :cancel_fines, only: [:new, :create]
    resources :special_offers, only: [:new, :create]
  end


  namespace :api do
    namespace :v1 do
      resources :buffets, only: [:index, :show] do
        resources :event_types, only: [:index]
      end
      get 'availability_check', to: 'event_types#availability_check'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cadê Buffet?</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= stylesheet_link_tag "border_card" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <div class="navbar-brand mb-0"><h2><%= link_to 'Cadê Buffet?', root_path, class:"nav-link" %></h2></div>

          <% unless owner_signed_in? %>
            <%= form_with url: buffet_search_buffets_path, method: :get do |f| %>
              <span class="d-flex align-items-center">
                <% f.label :query, 'Buscar Buffet:', class: "form-label" %>
                <%= f.text_field :query, placeholder: "Buscar Buffet", class: "form-control me-2" %>
                <%= f.submit 'Buscar', class: "btn btn-outline-success" %>
              </span>
            <% end %>
          <% end %>

          <% if user_signed_in? %>
            
            <span class="d-flex align-items-center">
              <span class="navbar-text me-2">
                <%= current_user.email %> | <%= User.model_name.human %>
              </span>
                <%= link_to 'Meus Pedidos', orders_path, class: "btn btn-info ms-2" %>
                <%= button_to 'Sair', destroy_user_session_path, method: :delete, class: "btn btn-danger ms-2" %>
            </span>

          <% elsif owner_signed_in? %>

            <% unless current_owner.buffet.nil? || !@buffet.valid? %>
              <h2 class="border-card-3 text-center" style="width: 16rem;"><%= link_to 'Meu Buffet', current_owner.buffet, class: "nav-link" %></h2>
            <% end %>

            <span class="d-flex align-items-center">
                <span class="navbar-text me-2">
                    <%= current_owner.email %> | <%= Owner.model_name.human %>
                </span>
                <% unless current_owner.buffet == nil || !current_owner.buffet.valid? %>
                  <%= link_to 'Pedidos', owner_orders_path, class: "btn btn-info ms-2" %>
                <% end %>
                <%= button_to 'Sair', destroy_owner_session_path, method: :delete, class: "btn btn-danger" %>
            </span>

          <% else %>
            <% unless request.path == home_choice_path %>
              <%= link_to 'Entrar', home_choice_path, class: "btn btn-primary" %>
            <% end %>
          <% end %>

        </div>
      </nav>
    </header>
    <main class="container">
      <% if notice.present? %>
        <p class="notice alert alert-info" role="alert"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p class="alert alert-danger" role="alert"><%= alert %></p>
      <% end %>

      <%= yield %>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>